# Generated by Django 3.1.7 on 2021-03-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github_url',
            field=models.URLField(default='https://github.com/TobiAdeniyi'),
            preserve_default=False,
        ),
    ]
